backend:
  name: github
  repo: Winwxn/Portfolio
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "database"
    label: "จัดการข้อมูลผลงาน (Database)"
    files:
      - label: "รวมผลงานทั้งหมด (All Projects)"
        name: "projects_db"
        file: "data/database.json"
        fields:
          - name: "projects"
            label: "รายชื่อโปรเจกต์ (Projects)"
            widget: "list"
            summary: "{{fields.title}} - {{fields.category}}"
            fields:
              - name: "title"
                label: "ชื่อโปรเจกต์ (Project Title)"
                widget: "string"
              - name: "category"
                label: "หมวดหมู่ผลงาน (Category)"
                widget: "select"
                options: ["Graphic Design", "Video Editor", "Highlight Graphic", "Highlight Video"]
              - name: "items"
                label: "รายการรูปภาพ/วิดีโอ (Items)"
                widget: "list"
                summary: "{{fields.description}}"
                fields:
                  - name: "url"
                    label: "ลิงก์ Google Drive"
                    widget: "string"
                  - name: "description"
                    label: "รายละเอียด (จำเป็น)"
                    widget: "text"
                    required: true
